# Generated by Django 5.2.7 on 2025-11-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
