# Generated by Django 5.2.7 on 2025-11-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_period', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wishlist_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saving_plan', to='api.wishlistitem')),
            ],
        ),
    ]
